name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build gcc-arm-none-eabi binutils-arm-none-eabi clang-format cppcheck

      - name: Check formatting
        run: |
          find . -path ./build -prune -o  -path ./components/freertos -prune -o -path ./components/f103-hal -prune -o
          -path ./components/littlefs -prune -o -path ./components/ascon-suite -prune -o -path ./components/cmsis-device-f1
          -prune -o -path ./components/etl -prune -o -path ./components/Unity -prune -o -path ./components/RTT -prune -o
          \( -name "*.cpp" -o -name "*.c" -o -name "*.h" -o -name "*.hpp" \) -print | xargs clang-format --dry-run --Werror

      - name: Configure
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=TRUE -G Ninja

      - name: Build
        run: cmake --build build --target build
      
      - name: Static analysis
        run: cmake --build build --target cppcheck
